name: Snyk Monitor
on: 
  push:
    branches:
      - master
jobs:
  security-open_source-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v3
        with:
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.5
      - name: Snyk monitor
        run: cd ./gradle; snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  security-open_source-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk monitor
        uses: snyk/actions/node@master
        with:
          command: monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  security-open_source-generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v3
      - name: Snyk monitor
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  security-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: build container image
        run: docker build -t nodejs-terraform-example:latest -f Dockerfile
      - name: snyk Monitor
        run: snyk container monitor nodejs-terraform-example:latest --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  security-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: snyk test (IaC)
        run: snyk iac describe
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  #security-code:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@master
  #    - uses: snyk/actions/setup@master
  #    - name: snyk test (code)
  #      run: snyk code test
  #      env:
  #        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
