name: Snyk Check (Open Source, Container, IaC, Code)
on: push
jobs:
  security-open_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: snyk/actions/setup@master
        uses: actions/setup-node@v3
      - name: snyk test (open source)
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  security-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: snyk/actions/setup@master
      - name: build container image
        run: docker build -t nodejs-terraform-example:latest -f Dockerfile
      - name: snyk test (container)
        run: snyk container test nodejs-terraform-example:latest --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  security-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: snyk/actions/setup@master
      - name: snyk test (IaC)
        run: snyk iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  security-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        uses: snyk/actions/setup@master
      - name: snyk test (code)
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}